name: AlohaHoes
author: Shipsterns
version: 1.0
main: me.krispin.hoes.HarvesterHoes
description: Custom Harvester Hoes plugin by Shipsterns

commands:
  harvesterhoe:
    usage: /<command>
    description: Gives player harvester hoe
    aliases: [hoe, harvesterhoes]
  upgrades:
    usage: /<command>
    description: Opens upgrades inventory
  essence:
    usage: /<command>
    description: essence balance
  givehoe:
    usage: /<command>
    description: gives a hoe